"""Create PostGIS-backed risk intelligence persistence."""
from django.contrib.gis.db import models as gis_models
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="RiskZone", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=160)), ("state", models.CharField(blank=True, db_index=True, max_length=80)), ("geometry", gis_models.PolygonField(srid=4326)), ("centroid", gis_models.PointField(blank=True, null=True, srid=4326)), ("area", models.FloatField(default=0)), ("risk_priority", models.PositiveSmallIntegerField(db_index=True, default=0)), ("flood_prone", models.BooleanField(db_index=True, default=False)), ("active", models.BooleanField(db_index=True, default=True)), ("population", models.PositiveIntegerField(default=0)), ("metadata", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True))], options={"ordering": ["-risk_priority", "name"]}),
        migrations.CreateModel(name="HistoricalFloodEvent", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("occurred_at", models.DateTimeField(db_index=True)), ("location", gis_models.PointField(srid=4326)), ("severity", models.PositiveSmallIntegerField()), ("state", models.CharField(blank=True, db_index=True, max_length=80)), ("source", models.CharField(max_length=120)), ("metadata", models.JSONField(blank=True, default=dict)), ("external_id", models.CharField(max_length=160, unique=True)), ("created_at", models.DateTimeField(auto_now_add=True))], options={"ordering": ["-occurred_at"]}),
        migrations.CreateModel(name="RiskAssessment", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("score", models.PositiveSmallIntegerField()), ("level", models.CharField(max_length=20)), ("confidence", models.FloatField()), ("breakdown", models.JSONField(default=dict)), ("assessed_at", models.DateTimeField(db_index=True)), ("zone", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assessments", to="risk.riskzone"))], options={"ordering": ["-assessed_at"]}),
        migrations.AddIndex(model_name="riskzone", index=models.Index(fields=["active", "risk_priority"], name="risk_riskzo_active_1ea566_idx")), migrations.AddIndex(model_name="historicalfloodevent", index=models.Index(fields=["state", "occurred_at"], name="risk_histor_state_83d6b3_idx")), migrations.AddIndex(model_name="riskassessment", index=models.Index(fields=["zone", "-assessed_at"], name="risk_riskas_zone_id_6a4363_idx")), migrations.AddConstraint(model_name="riskassessment", constraint=models.UniqueConstraint(fields=("zone", "assessed_at"), name="unique_zone_assessment_time")),
    ]
